name: youngfashions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#272727'
    - '#6f6f6f'
    - '#a0a0a0'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
