name: youngfashions
favicon: null
layout_spectrum: 0.24869
typography_spectrum: 0.31847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdd2d1'
    - '#fb514f'
    - '#ae9790'
    - '#120404'
    - '#972723'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
