name: youngfashions
favicon: null
layout_spectrum: 0.24869
typography_spectrum: 0.31847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbcfc1'
    - '#27262b'
    - '#9fa8b1'
    - '#414247'
    - '#8d2626'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
