name: youngfashions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edecf2'
    - '#020202'
    - '#585368'
    - '#b9adb1'
    - '#a57a6e'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
