name: youngfashions
favicon: null
layout_spectrum: 0.85196
typography_spectrum: 0.38867
title: YOUNGFASHIONS.CO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3dbe6'
    - '#9eaec1'
    - '#292a2e'
    - '#78879d'
    - '#525963'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
