typography_spectrum: 0.38867
color:
  brandColors:
    - '#d3dbe6'
    - '#9eaec1'
    - '#292a2e'
    - '#78879d'
    - '#525963'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.85196
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/13a7e4b5-8a98-49e8-a4ef-2c9934c8932a.svg
name: youngfashions
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: YOUNGFASHIONS.CO
purpose: []
